# SNF model

In [1]:
import networkx as nx 

from module1 import generating_HG as G_class
# ====================================================================
HG_instance = G_class.Generate_HG(sampling = True, num_Patients = 500)
HG = HG_instance.HG
Nodes = HG_instance.Nodes


Loading the dataframes...

We are SAMPLING

Use the patients inside the new DataFrame....
Dropping NaN visits
General Information:
---------------------------
Number of Patients = 500
Number of Diagnosis = 203
Number of procedures = 69
Number of Medication = 198
Number of Lab tests  = 499
Number of MicroBio   = 53
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Splitting lab tests


/lustre/home/almusawiaf/PhD_Projects/HGNN_Project2/Data_Generation/module1/generating_HG.py:77: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lab_df.loc[:, 'ITEMID_FLAG'] = lab_df['ITEMID'].astype(str) + '_' + lab_df['FLAG'].astype(str)


        HADM_ID     ITEMID_FLAG
22132  172056.0  51144_abnormal
22133  172056.0    51146_normal
22134  172056.0    51200_normal
22135  172056.0  51214_abnormal
22136  172056.0  51221_abnormal
22137  172056.0  51222_abnormal
22138  172056.0    51233_normal
22139  172056.0    51237_normal
22140  172056.0  51244_abnormal
22141  172056.0    51246_normal
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Extracting bipartite networks...

Extracting and adding data of Visits
SUBJECT_ID HADM_ID C V
     ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
275     504          64   172056      2.0       038
276     505          64   172056      3.0       995
277     506          64   172056      4.0       304
278     507          64   172056      5.0       112
279     508          64   172056      6.0       511

Extracting and adding data of Diagnosis
HADM_ID ICD9_CODE V D
     ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
275     504          64   172056      2.0       038
276     505    

In [2]:
from SNF import SNF_class 

SNF_inst = SNF_class(HG, Nodes)

print(SNF_inst.A.shape)

Getting the OHV for D
Getting the OHV for M
Getting the OHV for P
Getting the OHV for L
Getting the OHV for B
Measure the similarity
Fusing the different modules using SNF...
2 3
(500, 500)


In [10]:
import numpy as np

def expand_adjacency_matrix(matrix, m):
    # Get the original size (n x n) of the matrix
    n = matrix.shape[0]
    
    # Create a new (n+m) x (n+m) matrix filled with zeros
    expanded_matrix = np.zeros((n + m, n + m))
    
    # Copy the original matrix into the top-left corner of the expanded matrix
    expanded_matrix[:n, :n] = matrix
    
    return expanded_matrix

# Example adjacency matrix (4x4)
n = 4
adj_matrix = np.array([[0, 1, 0, 1],
                       [1, 0, 1, 0],
                       [0, 1, 0, 1],
                       [1, 0, 1, 0]])

# Expand it to a 7x7 matrix (n=4, m=3)
expanded_matrix = expand_adjacency_matrix(adj_matrix, m=3)

# Print the result
print(expanded_matrix)


[[0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
